// Date: 5/10/2014 3:37:33 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package magiciansartifice.main.core.client.magicalblocks;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelDragonAltar extends ModelBase
{
    //fields
    ModelRenderer altarPillar;
    ModelRenderer altarBase1;
    ModelRenderer altarBase2;
    ModelRenderer altarTop1;
    ModelRenderer altarTop2;
    ModelRenderer dragonOrb;
  
    public ModelDragonAltar() {
        textureWidth = 64;
        textureHeight = 32;
    
        altarPillar = new ModelRenderer(this, 23, 7);
        altarPillar.addBox(0F, 0F, 0F, 2, 8, 2);
        altarPillar.setRotationPoint(-1F, 13F, -1F);
        altarPillar.setTextureSize(64, 32);
        altarPillar.mirror = true;
        setRotation(altarPillar, 0F, 0F, 0F);
        altarBase1 = new ModelRenderer(this, 31, 0);
        altarBase1.addBox(0F, 0F, 0F, 4, 1, 4);
        altarBase1.setRotationPoint(-2F, 21F, -2F);
        altarBase1.setTextureSize(64, 32);
        altarBase1.mirror = true;
        setRotation(altarBase1, 0F, 0F, 0F);
        altarBase2 = new ModelRenderer(this, 32, 19);
        altarBase2.addBox(0F, 0F, 0F, 8, 2, 8);
        altarBase2.setRotationPoint(-4F, 22F, -4F);
        altarBase2.setTextureSize(64, 32);
        altarBase2.mirror = true;
        setRotation(altarBase2, 0F, 0F, 0F);
        altarTop1 = new ModelRenderer(this, 32, 9);
        altarTop1.addBox(0F, 0F, 0F, 8, 1, 8);
        altarTop1.setRotationPoint(-4F, 12F, -4F);
        altarTop1.setTextureSize(64, 32);
        altarTop1.mirror = true;
        setRotation(altarTop1, 0F, 0F, 0F);
        altarTop2 = new ModelRenderer(this, 14, 0);
        altarTop2.addBox(0F, 0F, 0F, 4, 2, 4);
        altarTop2.setRotationPoint(-2F, 13F, -2F);
        altarTop2.setTextureSize(64, 32);
        altarTop2.mirror = true;
        setRotation(altarTop2, 0F, 0F, 0F);
        dragonOrb = new ModelRenderer(this, 48, 0);
        dragonOrb.addBox(0F, 0F, 0F, 4, 4, 4);
        dragonOrb.setRotationPoint(-2F, 7F, -2F);
        dragonOrb.setTextureSize(64, 32);
        dragonOrb.mirror = true;
        setRotation(dragonOrb, 0F, 0F, 0F);
    }
  
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        altarPillar.render(f5);
        altarBase1.render(f5);
        altarBase2.render(f5);
        altarTop1.render(f5);
        altarTop2.render(f5);
        dragonOrb.render(f5);
    }
  
    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
  
    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}
